stylehub/about/urls.py
"""APP about URL Configuration"""
from typing import List

from about import views
from django.urls import path, resolvers

app_name = 'about'

urlpatterns: List[resolvers.URLPattern] = [
    path('', views.AboutUsView.as_view(), name='home'),
]

stylehub/api/urls.py
"""APP api URL Configuration"""
from typing import List

from api import views
from django.urls import path, resolvers

app_name = 'api'

urlpatterns: List[resolvers.URLPattern] = [
    path(
        'toggle_liked/<int:item_id>',
        views.ToggleLiked.as_view(),
        name='toggle_liked',
    ),
]

stylehub/auth/urls.py
"""urls for auth app"""
import django.contrib.auth.views as default_views
import django.urls

import auth.forms as auth_forms
import auth.views as auth_views

app_name = 'auth'

urlpatterns = [
    django.urls.path(
        'login/',
        auth_views.CustomLoginView.as_view(),
        name='login',
    ),
    django.urls.path(
        'logout/',
        default_views.LogoutView.as_view(
            template_name='home/index.html',
        ),
        name='logout',
    ),
    django.urls.path(
        'password_change/',
        default_views.PasswordChangeView.as_view(
            template_name='auth/password_change.html',
            form_class=auth_forms.PasswordChangeForm,
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_change/done/',
        auth_views.CustomChangePasswordDone.as_view(),
        name='password_change_done',
    ),
    django.urls.path(
        'password_reset/',
        default_views.PasswordResetView.as_view(
            template_name='auth/password_reset.html',
            form_class=auth_forms.PasswordResetForm,
        ),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        auth_views.CustomPasswordResetDone.as_view(),
        name='password_reset_done',
    ),
    django.urls.path(
        'reset/<uidb64>/<token>/',
        default_views.PasswordResetConfirmView.as_view(
            template_name='auth/password_change.html',
            form_class=auth_forms.PasswordResetConfirmForm,
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'reset/done/',
        auth_views.CustomPasswordResetComplete.as_view(),
        name='password_reset_complete',
    ),
    django.urls.path(
        'signup/',
        auth_views.SignUp.as_view(),
        name='signup',
    ),
    django.urls.path(
        'signup/done/', auth_views.SignUpDone.as_view(), name='signup_done'
    ),
    django.urls.path(
        'signup/<int:user_id>/<uuid:token>/',
        auth_views.SignUpConfirm.as_view(),
        name='signup_confirm',
    ),
]

stylehub/custom/urls.py
"""Endpoints of custom app"""
import django.urls

import custom.views

app_name = 'custom'

urlpatterns = [
    django.urls.path(
        '',
        custom.views.Main.as_view(),
        name='home',
    ),
]

stylehub/home/urls.py
"""APP home URL Configuration"""
from typing import List

from django.urls import path, resolvers

from home import views

app_name = 'home'

urlpatterns: List[resolvers.URLPattern] = [
    path('', views.Home.as_view(), name='home'),
]

stylehub/stylehub/urls.py
"""stylehub URL Configuration"""
from typing import Any

import django.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns: Any = [
    django.urls.path('admin/', admin.site.urls),
    django.urls.path('', django.urls.include('home.urls')),
    django.urls.path('about/', django.urls.include('about.urls')),
    django.urls.path('api/', django.urls.include('api.urls')),
    django.urls.path('auth/', django.urls.include('auth.urls')),
    django.urls.path('clothes/', django.urls.include('clothes.urls')),
    django.urls.path('custom/', django.urls.include('custom.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar.urls

    urlpatterns += [
        django.urls.path('__debug__/', django.urls.include(debug_toolbar.urls))
    ]

stylehub/templates/includes/card.html
{% load static i18n %}

<div class="card rounded-1 position-relative col col-12 col-md-6 col-lg-4 col-xl-3">
  <div id="product-2" class="single-product">
    <div class="card-item-header border-0 bg-gradient px-0">
      <span class="gender {{ item.gender }}">{{ item.gender }}</span>
      <a class="heart-logic heart{% if item in user_liked_items %}-fill{% endif %}" id="{{ item.id }}">
        <svg fill="#000000" width="22px" height="22px" viewBox="-3 0 36 36" version="1.1"
             xmlns="http://www.w3.org/2000/svg">
          <path d="M0.256 12.16q0.544 2.080 2.080 3.616l13.664 14.144 13.664-14.144q1.536-1.536 2.080-3.616t0-4.128-2.080-3.584-3.584-2.080-4.16 0-3.584 2.080l-2.336 2.816-2.336-2.816q-1.536-1.536-3.584-2.080t-4.128 0-3.616 2.080-2.080 3.584 0 4.128z"></path>
        </svg>
      </a>
      <img class="card-item-img bg-gradient" width="100%"
           src="{% if item.image %}{{ item.get_url }}{% else %}{% static 'img/default.png' %}{% endif %}"
           alt="Card image cap">
    </div>
    <div class="card-item-footer border-0 d-flex flex-column justify-content-between mx-3">
      <h3 class="product-title mb-0 mt-1">
        <a href="{% url 'clothes:wear' pk=item.id %}" class="text-decoration-none link-dark">{{ item.name }}</a>
      </h3>
      <p class="product-price text-end">{{ item.cost }}₽</p>
    </div>
  </div>
</div>

stylehub/templates/includes/collection_card.html
<div class="collection-container shadow-lg my-4 my-lg-5"
     style="background-image: {% if collection.image.get_url %}url({{ collection.image.get_url }}){% else %}url(https://ilyakhasanov.ru/images/background/83.png){% endif %};">
  <h2>{{ collection.name }}</h2>
  <span class="collection-block">
  {% for item in collection.items.all %}
    {% include 'includes/card.html' %}
  {% endfor %}
  </span>
</div>

stylehub/templates/includes/designer_card.html
{% load static i18n %}

<link rel="stylesheet" href="{% static 'css/designer_card.css' %}">
<div class="card designer_card rounded-1 position-relative col col-12 col-md-6 col-lg-4 col-xl-3">
  <img src="{% if designer.main_image %}
              {{ designer.main_image.get_url }}
            {% else %}
              https://www.pngarts.com/files/10/Default-Profile-Picture-Transparent-Images.png
            {% endif %}" alt="Аватарка дизайнера">
  <h3 class="designer_name position-absolute">
    {% if designer.first_name %}
      {{ designer.first_name }}
      {{ designer.last_name }}
    {% else %}
      {{ designer.username }}
    {% endif %}
  </h3>

  <div class="buyers position-absolute">
    <span class="buyers">Покупателей<br>{{ designer.buys }}</span>
  </div>
  <div class="rating position-absolute">
    <span class="buyers">Рейтинг<br>{{ designer.rating }}</span>
  </div>
</div>

stylehub/templates/includes/footer.html
{% load static i18n %}
<footer class="container-fluid border-top my-5">
  <div class="row row-cols-1 row-cols-sm-2 justify-content-between
          justify-content-md-around row-cols-md-5 pt-5 pb-2 px-5 my-3">
    <div class="col mb-3 me-5 footer-logo">
      <a href="{% url 'home:home' %}"
         class="d-flex align-items-start mb-3 link-body-emphasis text-decoration-none">
        <img src="{% static 'logo/logo.svg' %}" alt="Логотип" width="225" height="170">
      </a>
    </div>

    <div class="col mb-3">
      <h5><a href="{% url 'home:home' %}" class="link-dark text-decoration-none">StyleHub</a></h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">{% trans 'Дизайнеры' %}</a></li>
        <li class="nav-item mb-2"><a href="{% url 'clothes:home' %}"
                                     class="nav-link p-0 text-body-secondary">{% trans 'Каталог' %}</a></li>
        {% if user.is_designer %}
          <li class="nav-item mb-2">
            <a href="{% url 'clothes:create' form='collection' %}"
               class="nav-link p-0 text-body-secondary">{% trans 'Создать коллекцию' %}</a>
          </li>
        {% endif %}
      </ul>
    </div>

    <div class="col mb-3">
      <h5><a href="{% url 'custom:home' %}" class="link-dark text-decoration-none">CustomHub</a></h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2">
          <a href="{% url 'clothes:home' %}" class="nav-link p-0 text-body-secondary">{% trans 'Кастомеры' %}</a>
        </li>
        {% if user.is_designer %}
          <li class="nav-item mb-2">
            <a href="{% url 'clothes:create' form='item' %}"
               class="nav-link p-0 text-body-secondary">{% trans 'Создать вещь' %}</a>
          </li>
        {% endif %}
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Общее</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">{% trans 'Профиль' %}</a></li>
        <li class="nav-item mb-2">
          <a href="{% url 'clothes:liked_items' %}" class="nav-link p-0 text-body-secondary">{% trans 'Избранное' %}</a>
        </li>
        <li class="nav-item mb-2">
          <a href="{% url 'about:home' %}" class="nav-link p-0 text-body-secondary">{% trans 'О нас' %}</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item mb-2">
            <a href="{% url 'auth:logout' %}"
               class="nav-link p-0 text-body-secondary">{% trans 'Выйти' %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <p class="text-body-secondary text-center">© Все права защищены StyleHub {% now 'd.m.Y' %}</p>
</footer>

stylehub/templates/includes/header.html
{% load static i18n %}
<header class="mb-4">
  <div
          class="container-fluid px-4 d-flex flex-wrap
          align-items-center justify-content-between
          justify-content-xl-around py-1 border-bottom">
    <div class="col-lg-1 mb-2 mb-md-0">
      <a href="{% url 'home:home' %}" class="d-inline-flex link-body-emphasis text-decoration-none">
        <img src="{% static 'logo/logo.svg' %}" alt="Логотип" class="header-logo" width="100" height="100">
      </a>
    </div>
    <div class="d-md-flex col-5 justify-content-start d-none">
      <ul class="nav col-md-auto mb-2 justify-content-start gap-1 gap-lg-4 gap-xl-5 mb-md-0 mx-lg-4">
        {% with request.resolver_match.view_name as view_name %}
          <li class="dropdown show">
            <a href="#"
               class="nav-link link-dark px-2 dropdown-toggle{% if view_name == '' %} active-link{% endif %}"
               id="dropdownMenuButton" data-bs-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">{% trans 'Каталог' %}</a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'clothes:home' %}">{% trans 'StyleHub' %}</a>
              <a class="dropdown-item" href="{% url 'custom:home' %}">{% trans 'CustomHub' %}</a>
            </div>
          </li>
          <li class="mx-lg-4">
            <a href="{% url 'clothes:recommend' %}"
               class="nav-link link-dark px-2{% if view_name == 'clothes:recommend' %} active-link{% endif %}">{% trans 'Рекомендуем' %}</a>
          </li>
          <li class="mx-lg-4">
            <a href="{% url 'about:home' %}"
               class="nav-link link-dark px-2{% if view_name == 'about:home' %} active-link{% endif %}">{% trans 'О нас' %}</a>
          </li>
          {% if user.is_designer %}
          <li class="mx-lg-4">
            <a href="{% url 'clothes:create' form='collection' %}"
               class="nav-link px-2{% if view_name == 'clothes:create' %} active-link{% endif %}">{% trans 'Создать коллекцию' %}</a>
          </li>
          <li class="mx-lg-4">
            <a href="{% url 'clothes:create' form='item' %}"
               class="nav-link px-2{% if view_name == 'clothes:create' %} active-link{% endif %}">{% trans 'Создать вещь' %}</a>
          </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>

    <div class="text-end">
      {% if user.is_authenticated %}
        <span class="hearted px-3">
          <a href="{% url 'clothes:liked_items' %}"
             class="text-decoration-none">
            <svg fill="#000000" width="22px" height="22px" viewBox="-2 0 36 36" version="1.1"
                 xmlns="http://www.w3.org/2000/svg">
              <path d="M0.256 12.16q0.544 2.080 2.080 3.616l13.664 14.144 13.664-14.144q1.536-1.536 2.080-3.616t0-4.128-2.080-3.584-3.584-2.080-4.16 0-3.584 2.080l-2.336 2.816-2.336-2.816q-1.536-1.536-3.584-2.080t-4.128 0-3.616 2.080-2.080 3.584 0 4.128z"></path>
            </svg>
          </a>
        </span>
        <span class="profile px-3">
          <a href=""><img src="{% static 'img/profile.svg' %}" alt=""></a>
        </span>
      {% else %}
        <a href="{% url 'auth:login' %}" class="btn btn-outline-dark me-2">{% trans 'Войти' %}</a>
        <a href="{% url 'auth:signup' %}" class="btn btn-dark">{% trans 'Зарегистрироваться' %}</a>
      {% endif %}
    </div>
  </div>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</header>

stylehub/templates/includes/paginator.html
<nav class="paginator my-4" aria-label="Page navigation example">
  <ul class="pagination d-flex justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item d-inline-flex"><a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
    {% endif %}
    <li class="page-item d-inline-flex"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
      <li class="page-item d-inline-flex"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
    {% endif %}
  </ul>
</nav>