stylehub/api/urls.py
"""APP api URL Configuration"""
from typing import List

from api import views
from django.urls import path, resolvers

app_name = 'api'

urlpatterns: List[resolvers.URLPattern] = [
    path(
        'toggle_liked/<int:item_id>',
        views.ToggleLiked.as_view(),
        name='toggle_liked',
    ),
]

stylehub/clothes/urls.py
"""
clothes shop urlpatterns

add here your views
"""
import django.urls

import clothes.views

app_name = 'clothes'

urlpatterns = [
    django.urls.path(
        '',
        clothes.views.Main.as_view(),
        name='home',
    ),
    django.urls.path(
        'collections/',
        clothes.views.PopularCollections.as_view(),
        name='collections',
    ),
    django.urls.path(
        'designers/',
        clothes.views.PopularDesigners.as_view(),
        name='designers',
    ),
    django.urls.path(
        'unpopular/',
        clothes.views.UnpopularItems.as_view(),
        name='unpopular',
    ),
    django.urls.path(
        'wear/<int:pk>/', clothes.views.Wear.as_view(), name='wear'
    ),
    django.urls.path(
        'wear/<int:pk>/buy', clothes.views.BuyWear.as_view(), name='wear_buy'
    ),
    django.urls.path(
        'collection/<int:pk>/',
        clothes.views.Collection.as_view(),
        name='collection',
    ),
    django.urls.path(
        'designer/<int:pk>/',
        clothes.views.Designer.as_view(),
        name='designer',
    ),
    django.urls.path(
        'recommend/',
        clothes.views.Recommend.as_view(),
        name='recommend',
    ),
    django.urls.path(
        'create/<str:form>/',
        clothes.views.CreateSomething.as_view(),
        name='create',
    ),
    django.urls.path('orders/', clothes.views.Orders.as_view(), name='orders'),
    django.urls.path(
        'lovely/', clothes.views.Lovely.as_view(), name='lovely_designers'
    ),
    django.urls.path('orders/', clothes.views.Orders.as_view(), name='orders'),
    django.urls.path(
        'lovely/', clothes.views.Lovely.as_view(), name='lovely_designers'
    ),
    django.urls.path(
        'liked/', clothes.views.Saved.as_view(), name='liked_items'
    ),
]

stylehub/stylehub/urls.py
"""stylehub URL Configuration"""
from typing import Any

import django.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns: Any = [
    django.urls.path('admin/', admin.site.urls),
    django.urls.path('', django.urls.include('home.urls')),
    django.urls.path('about/', django.urls.include('about.urls')),
    django.urls.path('api/', django.urls.include('api.urls')),
    django.urls.path('auth/', django.urls.include('auth.urls')),
    django.urls.path('clothes/', django.urls.include('clothes.urls')),
    django.urls.path('custom/', django.urls.include('custom.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar.urls

    urlpatterns += [
        django.urls.path('__debug__/', django.urls.include(debug_toolbar.urls))
    ]

stylehub/clothes/models.py
"""Market models"""
from typing import Any

from django.db import models
from django.utils.translation import gettext_lazy as _
from django_cleanup import cleanup

import auth.models
import clothes.managers
import core.models
import market.models


@cleanup.select
class OrderClothes(market.models.Order):
    """
    OrderClothes model to store item buyings

    user: FK.
    designer: FK.
    sum: int. order cost
    item: FK
    status: choces statuses. order status
    created: datetime. creation datetime
    edited: editing datetime
    """

    objects = clothes.managers.OrderClothesManager()

    user = models.ForeignKey(
        verbose_name=_('заказчик'),
        to='user_auth.User',
        on_delete=models.SET_NULL,
        null=True,
        related_name='order_clothes_user',
    )

    designer = models.ForeignKey(
        verbose_name=_('исполнитель'),
        to='user_auth.User',
        on_delete=models.SET_NULL,
        null=True,
        related_name='order_clothes_designer',
    )

    sum = models.IntegerField(
        verbose_name=_('общая стоимость заказа'),
        null=False,
        blank=False,
    )
    item = models.ForeignKey(
        to='Item', on_delete=models.PROTECT, verbose_name=_('заказанная вещь')
    )

    class Meta:
        """Model settings"""

        verbose_name = _('заказ одежды')
        verbose_name_plural = _('заказы одежды')


@cleanup.select
class Collection(core.models.MainImageMixin, core.models.CreatedEdited):
    """
    category model for items collection
    describes item base collection: Haute Couture for example

    name: char[50]. Creature name.
    slug: char[50]. creature normalized name.
    created: datetime. Creation datetime.
    edited: datetime. Editing datetime.
    styles: ManyToManyField market.models.Style
    text: TextField - collection description
    designer: ForeignKey - to user_auth.User
    """

    objects = clothes.managers.CollectionManager()

    styles = models.ManyToManyField(
        market.models.Style,
        verbose_name=_('стиль коллекции'),
        related_name='item_styles',
    )

    name = models.CharField(
        verbose_name=_('название коллекции'),
        max_length=100,
    )

    text = models.TextField(verbose_name=_('описание коллекции'))

    designer = models.ForeignKey(
        to='user_auth.User',
        on_delete=models.CASCADE,
        verbose_name=_('дизайнер коллекции'),
        help_text=_('Укажите кто создал эту коллекцию'),
    )

    def save(self, *args: Any, **kwargs: Any) -> None:
        for item in Item.objects.pref_styles().filter(collection=self):
            for style in item.styles.all():
                if style not in self.styles.all():
                    self.styles.add(style)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    class Meta:
        """Model settings"""

        verbose_name = _('коллекция')
        verbose_name_plural = _('коллекции')


@cleanup.select
class Item(core.models.MainImageMixin, core.models.CreatedEdited):
    """
    Item models

    name: char[50]. Item name.
    designer: ForeignKey to auth.models.designer
    image: ImageField - image to describe main idea of item
    cost: PositiveBigIntegerField - describe how many this item cost
    text: TextField - item description
    category: ForeignKey to market.models.Category
    styles: ManyToManyField market.models.Style
    collection: ManyToOneField(ForeignKey) market.models.Collection
    created: datetime. Creation datetime.
    edited: datetime. Editing datetime.

    """

    objects = clothes.managers.ItemManager()

    item_genders = (
        ('male', _('Мужской')),
        ('female', _('Женский')),
        ('unisex', _('Унисекс')),
        ('childish', _('Детский')),
    )

    name = models.CharField(
        verbose_name=_('Название товара'),
        help_text=_(
            'Придумайте не длинное название, передающее основные черты товара'
        ),
        max_length=50,
    )

    designer = models.ForeignKey(
        verbose_name=_('дизайнер вещи'),
        related_name='item_designer',
        to='user_auth.User',
        on_delete=models.CASCADE,
    )

    gender = models.CharField(
        verbose_name=_('пол'),
        help_text=_('Кто будет носить эту вещь?'),
        choices=item_genders,
        default=item_genders[2][0],
        max_length=15,
        blank=False,
        null=False,
    )

    cost = models.IntegerField(
        verbose_name=_('стоимость товара'),
        help_text=_('добавьте стоимость вашего товара'),
    )

    text = models.TextField(
        verbose_name=_('описание товара'),
        help_text=_('опишите ваш товар'),
        null=True,
        blank=True,
    )

    category = models.ForeignKey(
        related_name='item_category',
        to=market.models.CategoryExtended,
        on_delete=models.CASCADE,
        verbose_name=_('категория товара'),
        help_text=_('указывает на категорию, к которой относится товар'),
    )

    styles = models.ManyToManyField(
        related_name='style',
        to=market.models.Style,
        verbose_name=_('стиль товара'),
        help_text=_('указывает к какому стилю принадлежит товар'),
    )

    collection = models.ForeignKey(
        to=Collection,
        on_delete=models.CASCADE,
        verbose_name=_('коллекция, в которой есть этот товар'),
        help_text=_('показывает участвует ли товар в каких-либо коллекциях'),
        related_name='items',
    )

    bought = models.IntegerField(
        verbose_name=_('куплено раз'),
        help_text=_('сколько раз купили этот товар'),
        default=0,
    )

    is_published = models.BooleanField(
        verbose_name='опубликован?',
        default=True,
    )

    def __str__(self) -> str:
        return self.name

    def buy(self, user: 'auth.models.User') -> OrderClothes:
        """creates an order with item and increments bought count"""
        self.bought += 1
        self.save()
        return OrderClothes.objects.create(
            user=user,
            designer=self.designer,
            sum=self.cost,
            item=self,
        )

    def save(self, *args: Any, **kwargs: Any) -> None:
        super().save()
        self.collection.save()

    class Meta:
        """Model settings"""

        verbose_name = _('вещь')
        verbose_name_plural = _('вещи')


Item._meta.get_field('image').default = 'defaults/item.png'


@cleanup.select
class ItemPicture(core.models.MainImageMixin):
    """
    models realise pictures gallery for item
    picture: ImageField one of many item picture
    item: ManyToOne shows for what item this picture
    """

    objects = clothes.managers.ItemPictureManager()
    item = models.ForeignKey(
        to=Item,
        on_delete=models.CASCADE,
        verbose_name=_('галерея изображений товара'),
        help_text=_('добавьте как можно болеее информативные фотографии'),
        related_name='images',
    )

    class Meta:
        """Model settings"""

        verbose_name = _('фотография вещи')
        verbose_name_plural = _('фотографии вещей')


class Evaluation(market.models.Evaluation):
    """
    Evalution on items from users

    created: datetime. creation datetime
    edited: datetime. editing datetime
    user: QuerySet[auth.models.User]. User who evaluated Item.
    item: QuerySet[market.models.Item]. Item for Evaluation
    rating: models.PositiveSmallIntegerField(int) Rating of evaluation
            from EVALUATION_VALUE_CHOICES
    goods: models.TextField(str) Good sides of Item
    negatives: models.TextField(str) Bad sides of Item
    text: models.TextField(str) Evaluation description
    """

    item = models.ForeignKey(
        to=Item,
        on_delete=models.CASCADE,
        verbose_name=_('товар'),
        help_text=_('товар, к которому оставили отзыв'),
        related_name='evaluations',
    )

    class Meta:
        """Model settings"""

        verbose_name = _('отзыв')
        verbose_name_plural = _('отзывы')

stylehub/clothes/forms.py
"""
clothes forms
"""
from typing import Any, List, Optional, Tuple

from django import forms
from django.core.files.uploadedfile import UploadedFile
from django.db.models import QuerySet
from django.utils.translation import gettext_lazy as _

import auth.models
import clothes.models
import market.models


def get_choices(
    queryset: QuerySet[Any], field1: str, field2: str
) -> List[Tuple[Any, Any]]:
    """returns list of choices from queryset"""
    choices = []
    for obj in queryset.iterator():
        choices.append((obj.__dict__[field1], obj.__dict__[field2]))
    return choices


class BaseDesignerForm(forms.ModelForm[Any]):
    """abstract designer form that have initial designer=request.user"""

    def __init__(
        self,
        *args: Any,
        designer: Optional[auth.models.User] = None,
        **kwargs: Any
    ):
        super().__init__(*args, **kwargs)
        designer_field = self.fields.get('designer')
        styles_field = self.fields.get('styles')

        designer_field.widget = forms.widgets.HiddenInput()
        if designer is not None:
            designer_field.initial = designer

        styles_field.choices = get_choices(
            market.models.Style.objects.all().only('id', 'name'),
            'id',
            'name',
        )


class CollectionCreateForm(BaseDesignerForm):
    """form that creates a new collection"""

    class Meta:
        """form settings"""

        model = clothes.models.Collection
        fields = [
            model.name.field.name,
            model.image.field.name,
            model.styles.field.name,
            model.text.field.name,
            model.designer.field.name,
        ]
        widgets = {
            model.name.field.name: forms.widgets.TextInput(
                attrs={'class': 'form-control'}
            ),
            model.image.field.name: forms.widgets.FileInput(
                attrs={'class': 'form-control'}
            ),
            model.styles.field.name: forms.widgets.SelectMultiple(
                attrs={'class': 'form-control'}
            ),
            model.text.field.name: forms.widgets.Textarea(
                attrs={'class': 'form-control'}
            ),
            model.designer.field.name: forms.widgets.Select(
                attrs={'class': 'form-control'}
            ),
        }


class ItemCreateForm(BaseDesignerForm):
    """form that creates a new collection"""

    def __init__(
        self,
        *args: Any,
        designer: Optional[auth.models.User] = None,
        **kwargs: Any
    ):
        super().__init__(*args, designer=designer, **kwargs)
        gallery_field = self.fields.get('gallery')
        category_field = self.fields.get('category')
        collection_field = self.fields.get('collection')

        gallery_field.label = _('Галерея')
        gallery_field.help_text = _('Приложите допольнительные фото')

        category_field.choices = get_choices(
            market.models.CategoryExtended.objects.all(), 'id', 'name'
        )

        collection_field.choices = get_choices(
            clothes.models.Collection.objects.filter(designer=designer),
            'id',
            'name',
        )

    gallery = forms.FileField(
        label='Приложенные файлы',
        required=False,
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
                'multiple': True,
            }
        ),
    )

    def save(
        self, commit: bool = True, files: Optional[List[UploadedFile]] = None
    ) -> Any:
        """custom save method to create ItemPicture objects for item gallery"""
        item = super().save(commit)
        if files:
            clothes.models.ItemPicture.objects.create_many(
                images=files, item=item
            )
        return item

    class Meta:
        """form settings"""

        model = clothes.models.Item
        fields = [
            model.name.field.name,
            model.image.field.name,
            'gallery',
            model.cost.field.name,
            model.category.field.name,
            model.collection.field.name,
            model.styles.field.name,
            model.gender.field.name,
            model.text.field.name,
            model.designer.field.name,
        ]
        widgets = {
            model.name.field.name: forms.widgets.TextInput(
                attrs={'class': 'form-control'}
            ),
            model.image.field.name: forms.widgets.FileInput(
                attrs={'class': 'form-control'}
            ),
            model.cost.field.name: forms.widgets.NumberInput(
                attrs={'class': 'form-control'}
            ),
            model.category.field.name: forms.widgets.Select(
                attrs={'class': 'form-control'},
            ),
            model.collection.field.name: forms.widgets.Select(
                attrs={'class': 'form-control'},
            ),
            model.styles.field.name: forms.widgets.SelectMultiple(
                attrs={'class': 'form-control'}
            ),
            model.gender.field.name: forms.widgets.Select(
                attrs={'class': 'form-control'},
            ),
            model.text.field.name: forms.widgets.Textarea(
                attrs={'class': 'form-control'}
            ),
            model.designer.field.name: forms.widgets.Select(
                attrs={'class': 'form-control'}
            ),
        }

stylehub/templates/clothes/collection.html
{% extends 'core/base.html' %}

{% block content %}
	{{ collection }}
	{{ collection.items }}
{% endblock %}

stylehub/templates/clothes/collections.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="item-table d-flex flex-row flex-wrap justify-content-center">
    {% for collection in page_obj %}
      {% include 'includes/collection_card.html' %}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}

stylehub/templates/clothes/designer_detail.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
  <form enctype="multipart/form-data" method="post" class="form-example">
    {% csrf_token %}
    {% for field in user_form %}
      <div class="py-2">
        <span>{{ field.label_tag }}</span>
        {{ field }}
      <p class="range_label d-inline-block"></p>
      {% for error in field.errors %}
        <p class='text-danger'> {{ error|escape }} </p>
      {% endfor %}
      </div>
    {% endfor %}
    <p>Коллекции дизайнера:
      {% for collection in collections %}
        {{ collection.name }}&nbsp;&nbsp;&nbsp;
      {% endfor %}
    </p>
    {% for field in designer_form %}
      <div>
        <span>{{ field.label_tag }}</span>
        {{ field }}
      </div>
      <p class="range_label d-inline-block"></p>
    {% endfor %}
    {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
            <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
            {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
      </div>
    {% endif %}
  </form>
{% endblock %}

stylehub/templates/clothes/designers.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="item-table d-flex flex-row flex-wrap justify-content-center">
    {% for designer in page_obj %}
      {% include 'includes/designer_card.html' %}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}

stylehub/templates/clothes/index.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
  {% if designers %}
    <div class="head-view">
      <h1 class="head-view-category"><span>{% trans 'Популярные дизайнеры' %}</span><a
              href="{% url 'clothes:designers' %}" class="to-paginator">{% trans 'Более...' %}</a></h1>
    </div>
    <p class="head-view-category-detail">
      {% trans 'Они нравятся большей части нашей аудитории, посмотрите, может вам понравится что то из их работ' %}
    </p>
    <section class="container my-3 d-flex gap-4 row justify-content-start">
      {% for designer in designers %}
        {% include 'includes/designer_card.html' %}
      {% empty %}
        <h4 class="text-center">На данный момент нет ни одного дизайнера</h4>
      {% endfor %}
    </section>
  {% endif %}
  {% if collections %}
    <div class="head-view">
      <h1 class="head-view-category"><span>{% trans 'Популярные коллекции' %}</span><a
              href="{% url 'clothes:collections' %}" class="to-paginator">{% trans 'Более...' %}</a></h1>
      <p class="head-view-category-detail">
        {% trans 'Эти коллекции больше всего понравились нашим пользователям, попробуйте эти вещи на себе!' %}
      </p>
    </div>
    {% for collection in collections %}
      {% if collection.items.count %}
        {% include 'includes/collection_card.html' %}
      {% endif %}
    {% empty %}
      <h4 class="text-center">На данный момент нет ни одной коллекции</h4>
    {% endfor %}
  {% endif %}
  <div class="head-view">
    <h1 class="head-view-category"><span>{% trans 'Недооценённые работы' %}</span><a
            href="{% url 'clothes:unpopular' %}" class="to-paginator">{% trans 'Более...' %}</a></h1>
    <p class="head-view-category-detail">
      {% trans 'Мы стараемся помочь каждому дизайнеру стать популярным, поэтому публикуем их работы здесь.' %}
    </p>
  </div>
  <div class="item-table d-flex flex-row flex-wrap justify-content-center">
    {% for item in unpopular %}
      {% include 'includes/card.html' %}
    {% empty %}
      <h4 class="text-center">Все работы на данный момент популярны)</h4>
    {% endfor %}
  </div>
{% endblock %}

stylehub/templates/clothes/items.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="item-table d-flex flex-row flex-wrap justify-content-center">
    {% for item in page_obj %}
      {% include 'includes/card.html' %}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}

stylehub/templates/clothes/liked.html
{% extends 'core/base.html' %}
{% load static i18n %}
{% block content %}
  <h1 class="text-center mb-4">{% trans 'Понравившиеся товары' %}</h1>
  <div class="d-flex gap-4">
  {% for item in items %}
    {% include 'includes/card.html' %}
  {% empty %}
    <h5 class="text-center my-5">{% trans 'Вы пока не добавили ни одного товара' %}</h5>
  {% endfor %}
  </div>
{% endblock %}

stylehub/templates/clothes/lovely.html
{% for designer in designers %}
  <p>{{ designer.username }}</p>
{% endfor %}

stylehub/templates/clothes/orders.html
{% for order in orders %}
  <p> {{ order.status }} </p>
  <p> {{ order.edited }} </p>
{% endfor %}

stylehub/templates/clothes/recommend.html
{% extends 'core/base.html' %}

{% block content %}
  {% for collection in collections %}
    {% include 'includes/collection_card.html' %}
  {% endfor %}
{% endblock %}

stylehub/templates/clothes/wear.html
{% extends 'core/base.html' %}
{% load i18n support static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/item_page.css' %}">
{% endblock %}

{% block content %}
  <div class="item-content">
    <div id="carouselExampleControls" class="item-gallery carousel slide" data-bs-ride="carousel">
      <ol class="carousel-indicators">
        <li data-bs-target="#{{ forloop.counter }}" data-bs-slide-to="0" class="active"></li>
        {% for image in item.images.all %}
          <li data-bs-target="#{{ forloop.counter }}" data-bs-slide-to="{{ forloop.counter }}"></li>
        {% endfor %}
      </ol>
      <div class="carousel-inner">
        {% with photo_px='500x400' %}
          <div class="carousel-item active">
            <img class="d-block w-100"
                 src="{% get_image_px image=item px=photo_px crop='center' quality=70 %}"
                 alt="">
          </div>
          {% for image in item.images.all %}
            <div class="carousel-item">
              <img class="d-block w-100"
                   src="{% get_image_px image=image px=photo_px crop='center' quality=70 %}"
                   alt="First slide">
            </div>
          {% endfor %}
        {% endwith %}
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only"></span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only"></span>
      </a>
    </div>
    <div class="item-head">
      <h1 class="item-name mb-3">
        {{ item.name.capitalize }}
      </h1>
      <h2 class="designed-by">Designed by: <a class="text-decoration-none designer-url"
                                              href="{% url 'clothes:designer' pk=item.designer.designer_profile.id %}">{{ item.designer }}</a>
      </h2>
      <span class="item-category mb-4">{% trans item.category.name.capitalize %}</span>
      <span class="item-tags pt-0 my-4">{% comma_separated_styles item.styles.all %}</span>
      <span class="item-tags pt-0 my-4">{{ item.collection }} Colection</span>
      <p class="my-4"><span class="sz-20">Пол: </span>{% trans item.get_gender_display %}</p>
      <span class="align-items-baseline d-flex gap-5">
        <a href="{% url 'clothes:wear_buy' pk=item.id %}" class="btn btn-dark btn-buy">{% trans 'Купить' %}</a>
        <span class="me-3 cost">{{ item.cost }}₽</span>
      </span>
    </div>
    {% if item.text %}
      <div class="item-description">{{ item.text|replace_newline|safe }}</div>
    {% endif %}
    {#  <div class="evoluation-form container ms-2">#}
    {#    {% if user.is_authenticated %}#}
    {#      <form method="post">#}
    {#        {% csrf_token %}#}
    {#        {% for field in evaluation_form %}#}
    {#          {{ field }}#}
    {#          {{ field.label_tag }}#}
    {#          <p class="range_label d-inline-block"></p>#}
    {#          {% if field.help_text %}#}
    {#            <p class='form-text'> {{ field.help_text }} </p>#}
    {#          {% endif %}#}
    {#          {% for error in field.errors %}#}
    {#            <p class='text-danger'> {{ error|escape }} </p>#}
    {#          {% endfor %}#}
    {#        {% endfor %}#}
    {#        <div class="d-inline-block w-75">#}
    {#          <div class="d-flex justify-content-end gap-1">#}
    {#            <button type="submit" class="btn btn-primary">Отправить</button>#}
    {#            {% if evaluation %}#}
    {#              <a class="btn btn-danger" href={% url 'rating:delete_evaluation' item_id=item.id %}>Удалить</a>#}
    {#            {% endif %}#}
    {#          </div>#}
    {#        </div>#}
    {#        <script src="{% static 'js/item_page.js' %}"></script>#}
    {#      </form>#}
    {#    {% else %}#}
    {#      <p><a href="{% url "authorisation:login" %}">Авторизуйтесь</a>, чтобы оставить отзыв.</p>#}
    {#    {% endif %}#}
    {#    <p class="mt-3"> Среднее: {{ average }} </p>#}
    {#    <p> Количество отзывов: {{ count }} </p>#}
    {#  </div>#}
  </div>
{% endblock %}